const items = [{
        id: 1,
        name: 'Discgolf',
        language: 'Vue.JS',
        title: 'Startsida för discgolf',
        description: 'Har försökt att skapa en kopia av discgolf.se startsida. Den är inte helt färdig än, men det mest är finns där.',
        githubLink: 'https://github.com/Jockesvensson/Discgolf/blob/master/README.md',
        websiteLink: 'https://discgolf-3e062.web.app/',
        imageStart: require('../assets/discgolfStart.png'),
        imageInfo: require('../assets/discgolfInfo.png'),
    },
    {
        id: 2,
        name: 'Platsbanken',
        language: 'Vue.JS',
        title: 'Hemsida för att söka jobb',
        description: 'Har försökt att skapa en kopia av arbetsförmedlingens platsbank. Allt finns inte tillgängligt än och det finns vissa buggar, men i sin helhet så fungerar den.',
        githubLink: 'https://github.com/Jockesvensson/SearchJob',
        websiteLink: 'https://searchjob-9c000.firebaseapp.com/',
        imageStart: require('../assets/PlatsbankenStart.png'),
        imageInfo: require('../assets/PlatsbankenInfo.png'),
    },
    {
        id: 3,
        name: 'Hälsoapplikation',
        language: 'Vue.JS',
        title: 'Hemsida för att räkna kalorier',
        description: 'Mitt första försökt till att skapa en hemsida i Vue.JS. Använde en api för att söka ut näringsinnehållet i råvarorna och sedan firebase för att lagra data/skapa profiler.',
        githubLink: 'https://github.com/Jockesvensson/FoodTracker',
        websiteLink: 'https://jocke-vue-api-auth.firebaseapp.com/',
        imageStart: require('../assets/foodStart.png'),
        imageInfo: require('../assets/foodInfo.png'),
    },
    {
        id: 4,
        name: 'Webshop',
        language: 'Vue.JS',
        title: 'En enklare webshop',
        description: 'Min andra hemsida skapad i vue.js, denna gång mer fokus på att lära mig Vue/Vuex Store och dess funktioner.',
        githubLink: 'https://github.com/Jockesvensson/WebshopV2',
        websiteLink: 'https://webshopv2-df58e.web.app/',
        imageStart: require('../assets/Webshop1Start.png'),
        imageInfo: require('../assets/Webshop1Info.png'),
    },
    {
        id: 5,
        name: 'Webshop',
        language: 'HTML/CSS/jQuery',
        title: 'Startsida på en webshop',
        description: 'En testuppgift jag skulle lösa. Fick en bildmall som jag skulle efterskapa.',
        githubLink: 'https://github.com/Jockesvensson/WebshopPHP',
        websiteLink: 'http://jockesvensson.tmp.wikinggruppen.info/',
        imageStart: require('../assets/Webshop2Start.png'),
        imageInfo: require('../assets/WebShop2Info.png'),
    },
    {
        id: 6,
        name: 'Huslånekalkyl',
        language: 'Vue.JS',
        title: 'En lånekalkyl för att köpa hus',
        description: 'Ville skapa en egen lånekalkyl till att köpa en bostad.',
        githubLink: 'https://github.com/Jockesvensson/HouseLoan',
        websiteLink: 'https://houseloan-fab74.web.app/',
        imageStart: require('../assets/HouseLoanStart.png'),
        imageInfo: require('../assets/HouseLoanInfo.png'),
    },
    {
        id: 7,
        name: 'Hitta lediga jobb',
        language: 'ASP.NET',
        title: 'Hemsida som listar lediga jobb',
        description: 'Ville testa att hämta information via en API. Skapade därför en enklare hemsida som med hjälp av arbetsförmedlingens öppna API visar alla (100 st) lediga jobb i en förvald stad.',
        githubLink: 'https://github.com/Jockesvensson/Afs-API',
        imageStart: require('../assets/PlatsbankenASPStart.png'),
        imageInfo: require('../assets/PlatsbankenASPInfo.png'),
    },
    {
        id: 8,
        name: 'Hitta lediga jobb',
        language: 'Flutter/Dart',
        title: 'Mobilapplikation som listar lediga jobb',
        description: 'En mobilapplikation som använder sig av arbetsförmedlingens öppna API. Den presenterar alla lediga jobb i en förvald stad. En funktion för att ändra stad är påbörjad i appen men ej redo.',
        githubLink: 'https://github.com/Jockesvensson/FlutterApiApplicaiton',
        imageStart: require('../assets/FlutterStart.png'),
        imageInfo: require('../assets/FlutterInfo.png'),
    },
    {
        id: 9,
        name: 'Min hemsida',
        language: 'Vue.JS',
        title: 'Information/portfoliosida',
        description: 'Skapade en hemsida ägnad för mig själv. Där det finns lite information om mig samt där jag kan ladda upp tidigare projekt som jag har skapat. Det här är en nya version än min första hemsida.',
        githubLink: 'https://github.com/Jockesvensson/PortfolioPage',
        websiteLink: 'https://webshopv2-df58e.web.app/',
        imageStart: require('../assets/Hemsida1Start.png'),
        imageInfo: require('../assets/Hemsida1Info.png'),
    },
    {
        id: 10,
        name: 'Min hemsida',
        language: 'HTML/CSS/jQuery',
        title: 'Information/portfoliosida',
        description: 'Skapade en hemsida ägnad för mig själv. Där det finns lite information om mig samt där jag kan ladda upp tidigare projekt som jag har skapat. Detta är den första versionen.',
        githubLink: 'https://github.com/Jockesvensson/JockeWebSite',
        imageStart: require('../assets/Hemsida1Start.png'),
        imageInfo: require('../assets/Hemsida1Info.png'),
    },
]

export default items;